#include "backend/player_command.hpp"
#include "natives.hpp"
#include "pointers.hpp"
#include "core/scr_globals.hpp"
#include "util/scripts.hpp"
#include "util/entity.hpp"

namespace big
{
	class ultimate_crash : player_command
	{
		using player_command::player_command;

		virtual CommandAccessLevel get_access_level()
		{
			return CommandAccessLevel::TOXIC;
		}

		virtual void execute(player_ptr player, const std::vector<std::uint64_t>& _args, const std::shared_ptr<command_context> ctx)
		{
			Ped PlayerPed = PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(g_player_service->get_selected()->id());
			Hash hash1 = rage::joaat("prop_dummy_01");
			Hash hash2 = rage::joaat("prop_dummy_car");
			Hash hash3 = rage::joaat("prop_dummy_light");
			Hash hash4 = rage::joaat("prop_dummy_plane");
			Hash hash5 = rage::joaat("prop_distantcar_night");
			Hash hash6 = rage::joaat("prop_distantcar_day");
			Hash hash7 = rage::joaat("hei_bh1_08_details4_em_night");
			Hash hash8 = rage::joaat("dt1_18_sq_night_slod");
			Hash hash9 = rage::joaat("ss1_12_night_slod");
			Hash hash10 = rage::joaat("h4_prop_bush_bgnvla_med_01");
			Hash hash11 = rage::joaat("h4_prop_bush_bgnvla_lrg_01");
			Hash hash12 = rage::joaat("h4_prop_bush_buddleia_low_01");
			Hash hash13 = rage::joaat("h4_prop_bush_ear_aa");
			Hash hash14 = rage::joaat("h4_prop_bush_ear_ab");
			Hash hash15 = rage::joaat("h4_prop_bush_fern_low_01");
			Hash hash16 = rage::joaat("h4_prop_bush_fern_tall_cc");
			Hash hash17 = rage::joaat("h4_prop_bush_mang_ad");
			Hash hash18 = rage::joaat("h4_prop_bush_mang_low_aa");
			Hash hash19 = rage::joaat("h4_prop_bush_mang_low_ab");
			Hash hash20 = rage::joaat("h4_prop_bush_seagrape_low_01");//irlstiln crash
			Hash hash21 = rage::joaat("prop_h4_ground_cover");
			Hash hash22 = rage::joaat("h4_prop_weed_groundcover_01");
			Hash hash23 = rage::joaat("h4_prop_grass_med_01");
			Hash hash24 = rage::joaat("h4_prop_grass_tropical_lush_01");
			Hash hash25 = rage::joaat("h4_prop_grass_wiregrass_01");
			Hash hash26 = rage::joaat("h4_prop_weed_01_plant");
			Hash hash27 = rage::joaat("h4_prop_weed_01_row");
			Hash hash28 = rage::joaat("urbanweeds02_l1");
			Hash hash29 = rage::joaat("proc_forest_grass01");
			Hash hash30 = rage::joaat("prop_small_bushyba");
			Hash hash31 = rage::joaat("v_res_d_dildo_a");
			Hash hash32 = rage::joaat("v_res_d_dildo_b");
			Hash hash33 = rage::joaat("v_res_d_dildo_c");
			Hash hash34 = rage::joaat("v_res_d_dildo_d");
			Hash hash35 = rage::joaat("v_res_d_dildo_e");
			Hash hash36 = rage::joaat("v_res_d_dildo_f");
			Hash hash37 = rage::joaat("v_res_skateboard");
			Hash hash38 = rage::joaat("prop_battery_01");
			Hash hash39 = rage::joaat("prop_barbell_01");
			Hash hash40 = rage::joaat("prop_barbell_02");
			Hash hash41 = rage::joaat("prop_bandsaw_01");
			Hash hash42 = rage::joaat("prop_bbq_3");
			Hash hash43 = rage::joaat("v_med_curtainsnewcloth2");
			Hash hash44 = rage::joaat("bh1_07_flagpoles");
			Hash hash45 = 92962485;
			Hash hash46 = 310817095;
			Hash hash47 = -1288391198;
			STREAMING::REQUEST_MODEL(hash1);
			STREAMING::REQUEST_MODEL(hash2);
			STREAMING::REQUEST_MODEL(hash3);
			STREAMING::REQUEST_MODEL(hash4);
			STREAMING::REQUEST_MODEL(hash5);
			STREAMING::REQUEST_MODEL(hash6);
			STREAMING::REQUEST_MODEL(hash7);
			STREAMING::REQUEST_MODEL(hash8);
			STREAMING::REQUEST_MODEL(hash9);
			STREAMING::REQUEST_MODEL(hash10);
			STREAMING::REQUEST_MODEL(hash11);
			STREAMING::REQUEST_MODEL(hash12);
			STREAMING::REQUEST_MODEL(hash13);
			STREAMING::REQUEST_MODEL(hash14);
			STREAMING::REQUEST_MODEL(hash15);
			STREAMING::REQUEST_MODEL(hash16);
			STREAMING::REQUEST_MODEL(hash17);
			STREAMING::REQUEST_MODEL(hash18);
			STREAMING::REQUEST_MODEL(hash19);
			STREAMING::REQUEST_MODEL(hash20);
			STREAMING::REQUEST_MODEL(hash21);
			STREAMING::REQUEST_MODEL(hash22);
			STREAMING::REQUEST_MODEL(hash23);
			STREAMING::REQUEST_MODEL(hash24);
			STREAMING::REQUEST_MODEL(hash25);
			STREAMING::REQUEST_MODEL(hash26);
			STREAMING::REQUEST_MODEL(hash27);
			STREAMING::REQUEST_MODEL(hash28);
			STREAMING::REQUEST_MODEL(hash29);
			STREAMING::REQUEST_MODEL(hash30);
			STREAMING::REQUEST_MODEL(hash31);
			STREAMING::REQUEST_MODEL(hash32);
			STREAMING::REQUEST_MODEL(hash33);
			STREAMING::REQUEST_MODEL(hash34);
			STREAMING::REQUEST_MODEL(hash35);
			STREAMING::REQUEST_MODEL(hash36);
			STREAMING::REQUEST_MODEL(hash37);
			STREAMING::REQUEST_MODEL(hash38);
			STREAMING::REQUEST_MODEL(hash39);
			STREAMING::REQUEST_MODEL(hash40);
			STREAMING::REQUEST_MODEL(hash41);
			STREAMING::REQUEST_MODEL(hash42);
			STREAMING::REQUEST_MODEL(hash43);
			STREAMING::REQUEST_MODEL(hash44);
			STREAMING::REQUEST_MODEL(hash45);
			STREAMING::REQUEST_MODEL(hash46);
			STREAMING::REQUEST_MODEL(hash47);
			script::get_current()->yield(1s);
			STREAMING::HAS_MODEL_LOADED(hash1);
			STREAMING::HAS_MODEL_LOADED(hash2);
			STREAMING::HAS_MODEL_LOADED(hash3);
			STREAMING::HAS_MODEL_LOADED(hash4);
			STREAMING::HAS_MODEL_LOADED(hash5);
			STREAMING::HAS_MODEL_LOADED(hash6);
			STREAMING::HAS_MODEL_LOADED(hash7);
			STREAMING::HAS_MODEL_LOADED(hash8);
			STREAMING::HAS_MODEL_LOADED(hash9);
			STREAMING::HAS_MODEL_LOADED(hash10);
			STREAMING::HAS_MODEL_LOADED(hash11);
			STREAMING::HAS_MODEL_LOADED(hash12);
			STREAMING::HAS_MODEL_LOADED(hash13);
			STREAMING::HAS_MODEL_LOADED(hash14);
			STREAMING::HAS_MODEL_LOADED(hash15);
			STREAMING::HAS_MODEL_LOADED(hash16);
			STREAMING::HAS_MODEL_LOADED(hash17);
			STREAMING::HAS_MODEL_LOADED(hash18);
			STREAMING::HAS_MODEL_LOADED(hash19);
			STREAMING::HAS_MODEL_LOADED(hash20);
			STREAMING::HAS_MODEL_LOADED(hash21);
			STREAMING::HAS_MODEL_LOADED(hash22);
			STREAMING::HAS_MODEL_LOADED(hash23);
			STREAMING::HAS_MODEL_LOADED(hash24);
			STREAMING::HAS_MODEL_LOADED(hash25);
			STREAMING::HAS_MODEL_LOADED(hash26);
			STREAMING::HAS_MODEL_LOADED(hash27);
			STREAMING::HAS_MODEL_LOADED(hash28);
			STREAMING::HAS_MODEL_LOADED(hash29);
			STREAMING::HAS_MODEL_LOADED(hash30);
			STREAMING::HAS_MODEL_LOADED(hash31);
			STREAMING::HAS_MODEL_LOADED(hash32);
			STREAMING::HAS_MODEL_LOADED(hash33);
			STREAMING::HAS_MODEL_LOADED(hash34);
			STREAMING::HAS_MODEL_LOADED(hash35);
			STREAMING::HAS_MODEL_LOADED(hash36);
			STREAMING::HAS_MODEL_LOADED(hash37);
			STREAMING::HAS_MODEL_LOADED(hash38);
			STREAMING::HAS_MODEL_LOADED(hash39);
			STREAMING::HAS_MODEL_LOADED(hash40);
			STREAMING::HAS_MODEL_LOADED(hash41);
			STREAMING::HAS_MODEL_LOADED(hash42);
			STREAMING::HAS_MODEL_LOADED(hash43);
			STREAMING::HAS_MODEL_LOADED(hash44);
			STREAMING::HAS_MODEL_LOADED(hash45);
			STREAMING::HAS_MODEL_LOADED(hash46);
			STREAMING::HAS_MODEL_LOADED(hash47);

			{
				Vector3 coords = ENTITY::GET_ENTITY_COORDS(PlayerPed, true);
				OBJECT::CREATE_OBJECT(hash1, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash2, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash3, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash4, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash5, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash6, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash7, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash8, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash9, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash10, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash11, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash12, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash13, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash14, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash15, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash16, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash17, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash18, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash19, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash20, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash21, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash22, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash23, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash24, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash25, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash26, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash27, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash28, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash29, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash30, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash31, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash32, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash33, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash34, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash35, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash36, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash37, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash38, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash39, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash40, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash41, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash42, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash43, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash44, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash45, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash46, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::CREATE_OBJECT(hash47, coords.x, coords.y, coords.z, true, 1, 0);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash1, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash2, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash3, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash4, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash5, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash6, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash7, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash8, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash9, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash10, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash11, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash12, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash13, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash14, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash15, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash16, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash17, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash18, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash19, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash20, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash21, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash22, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash23, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash24, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash25, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash26, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash27, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash28, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash29, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash30, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash31, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash32, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash33, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash34, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash35, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash36, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash37, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash38, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash39, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash40, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash41, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash42, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash43, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash44, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash45, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash46, NULL, NULL);
				OBJECT::BREAK_OBJECT_FRAGMENT_CHILD(hash47, NULL, NULL);
				script::get_current()->yield(1s);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash1);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash2);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash3);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash4);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash5);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash6);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash7);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash8);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash9);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash10);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash11);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash12);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash13);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash14);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash15);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash16);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash17);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash18);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash19);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash20);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash21);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash22);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash23);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash24);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash25);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash26);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash27);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash28);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash29);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash30);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash31);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash32);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash33);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash34);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash35);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash36);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash37);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash38);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash39);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash40);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash41);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash42);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash43);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash44);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash45);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash46);
				STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(hash47);

				script::get_current()->yield(3s);

				//entity::delete_entity(hash1);
				//entity::delete_entity(hash2);
				//entity::delete_entity(hash3);
				//entity::delete_entity(hash4);
				//entity::delete_entity(hash5);
				//entity::delete_entity(hash6);
				//entity::delete_entity(hash7);
				//entity::delete_entity(hash8);
				//entity::delete_entity(hash9);
				//entity::delete_entity(hash10);
				//entity::delete_entity(hash11);
				//entity::delete_entity(hash12);
				//entity::delete_entity(hash13);
				//entity::delete_entity(hash14);
				//entity::delete_entity(hash15);
				//entity::delete_entity(hash16);
				//entity::delete_entity(hash17);
				//entity::delete_entity(hash18);
				//entity::delete_entity(hash19);
				//entity::delete_entity(hash20);
				//entity::delete_entity(hash21);
				//entity::delete_entity(hash22);
				//entity::delete_entity(hash23);
				//entity::delete_entity(hash24);
				//entity::delete_entity(hash25);
				//entity::delete_entity(hash26);
				//entity::delete_entity(hash27);
				//entity::delete_entity(hash28);
				//entity::delete_entity(hash29);
				//entity::delete_entity(hash30);
				//entity::delete_entity(hash31);
				//entity::delete_entity(hash32);
				//entity::delete_entity(hash33);
				//entity::delete_entity(hash34);
				//entity::delete_entity(hash35);
				//entity::delete_entity(hash36);
				//entity::delete_entity(hash37);
				//entity::delete_entity(hash38);
				//entity::delete_entity(hash39);
				//entity::delete_entity(hash40);
				//entity::delete_entity(hash41);
				//entity::delete_entity(hash42);
				//entity::delete_entity(hash43);
				//entity::delete_entity(hash44);
				//entity::delete_entity(hash45);
				//entity::delete_entity(hash46);
				//entity::delete_entity(hash47);
			}
		}
	};
	ultimate_crash g_ultimate_crash("ultimate", "Object Crash", "Blocked by most menus!", 0, false);
}